// src/routes/CreateRoute.tsx
import React, { useState, useEffect } from "react";
import { auth } from "../libs/firebase";
import { onAuthStateChanged, type User } from "firebase/auth";
import CreateMeetupForm from "../components/CreateMeetupForm";
import { navigateToTab } from "../libs/router";
import Icon from "../components/Icon";

interface Props {
  selectedLat: number | null;
  selectedLng: number | null;
  addressText: string;
  userLat: number | null;
  userLng: number | null;
  setSelectedLat: (lat: number | null) => void;
  setSelectedLng: (lng: number | null) => void;
  setAddressText: (text: string) => void;
}

export default function CreateRoute({
  selectedLat,
  selectedLng,
  addressText,
  userLat,
  userLng,
  setSelectedLat,
  setSelectedLng,
  setAddressText,
}: Props) {
  const [currentUser, setCurrentUser] = useState<User | null>(auth.currentUser);

  useEffect(() => {
    const unsub = onAuthStateChanged(auth, (user) => {
      setCurrentUser(user);
    });
    return unsub;
  }, []);

  function handleCreateSuccess() {
    setSelectedLat(null);
    setSelectedLng(null);
    setAddressText("");
    navigateToTab("my-meetups");
  }

  return (
    <section id="create-route" className="pb-20">
      <h2 className="section-title">Lên Kèo Chơi Mới</h2>
      {currentUser ? (
        <CreateMeetupForm
          selectedLat={selectedLat}
          selectedLng={selectedLng}
          addressText={addressText}
          userLat={userLat}
          userLng={userLng}
          setSelectedLat={setSelectedLat}
          setSelectedLng={setSelectedLng}
          setAddressText={setAddressText}
          onCreateSuccess={handleCreateSuccess}
        />
      ) : (
        <div className="cartoon-card locked-card p-10 bg-[#fffefb] text-center mt-5 border-3 border-[#1e1e24] shadow-neo rounded-2xl">
          <div className="locked-icon flex justify-center items-center mb-4 text-[#1e1e24]">
            <Icon name="lock" size={40} />
          </div>
          <h4 className="locked-title text-xl font-bold mb-2 text-[#1e1e24]">Cần Đăng Nhập Tài Khoản</h4>
          <p className="locked-description text-[0.95rem] font-semibold text-[#666666] max-w-[360px] mx-auto mb-6 leading-relaxed">
            Bạn cần đăng nhập tài khoản trước khi có thể tự thiết lập và lên kèo chơi boardgame mới nhé!
          </p>
          <a href="#/profile" className="login-link-btn inline-flex items-center gap-2 py-3 px-7 text-[0.95rem] font-extrabold border-3 border-[#1e1e24] rounded-lg bg-pastelYellow text-[#1e1e24] shadow-neo no-underline">
            <Icon name="key" size={16} />
            <span>Đi tới trang Đăng nhập</span>
          </a>
        </div>
      )}
    </section>
  );
}

// src/routes/CreateRoute.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { auth } from "../lib/firebase";
  import { onAuthStateChanged, type User } from "firebase/auth";
  import CreateMeetupForm from "../lib/CreateMeetupForm.svelte";
  import { navigateToTab } from "../lib/router.svelte";

  interface Props {
    meetups?: any[];
    selectedLat: number | null;
    selectedLng: number | null;
    addressText: string;
    userLat: number | null;
    userLng: number | null;
  }

  let {
    selectedLat = $bindable(null),
    selectedLng = $bindable(null),
    addressText = $bindable(""),
    userLat,
    userLng,
  }: Props = $props();

  let currentUser = $state<User | null>(auth.currentUser);

  onMount(() => {
    const unsub = onAuthStateChanged(auth, (user) => {
      currentUser = user;
    });
    return unsub;
  });

  function handleCreateSuccess() {
    selectedLat = null;
    selectedLng = null;
    addressText = "";
    // Chuyển hướng người dùng sang tab "Các Kèo" sau khi tạo thành công để xem danh sách
    navigateToTab("my-meetups");
  }
</script>

<section id="create-route" style="padding-bottom: 80px;">
  {#if currentUser}
    <CreateMeetupForm
      bind:selectedLat
      bind:selectedLng
      bind:addressText
      {userLat}
      {userLng}
      onCreateSuccess={handleCreateSuccess}
    />
  {:else}
    <!-- Unauthorized warning -->
    <div class="cartoon-card" style="padding: 40px; background-color: #fffefb; text-align: center; margin-top: 20px;">
      <span style="font-size: 3rem; display: block; margin-bottom: 16px;">🔒</span>
      <h4 style="font-size: 1.3rem; font-weight: 700; margin-bottom: 8px; color: var(--text-dark);">Cần Đăng Nhập Tài Khoản</h4>
      <p style="font-size: 0.95rem; font-weight: 500; color: var(--text-muted); max-width: 360px; margin: 0 auto 24px auto; line-height: 1.5;">
        Bạn cần đăng nhập tài khoản trước khi có thể tự thiết lập và lên kèo chơi boardgame mới nhé!
      </p>
      <a 
        href="#/profile" 
        class="btn btn-primary"
        style="display: inline-block; padding: 12px 28px; font-size: 0.95rem; font-weight: 800; border: 3px solid #1e1e24; border-radius: 8px; background-color: var(--pastel-yellow, #ffe869) !important; color: #1e1e24 !important; box-shadow: 4px 4px 0px #1e1e24; text-decoration: none;"
      >
        Đi tới trang Đăng nhập 🔑
      </a>
    </div>
  {/if}
</section>

<style>
</style>
