// src/routes/FilterRoute.svelte
<script lang="ts">
  import { goBack } from '../lib/router.svelte';
  import Icon from '../lib/Icon.svelte';

  interface Props {
    selectedCity: 'all' | 'HCM' | 'HN';
    selectedDistance: 'all' | '5' | '10';
    userLat: number | null;
    isTrackingGPS: boolean;
    gpsError: boolean;
    onApply: (city: 'all' | 'HCM' | 'HN', distance: 'all' | '5' | '10') => void;
  }

  let { 
    selectedCity = 'all', 
    selectedDistance = 'all', 
    userLat, 
    isTrackingGPS, 
    gpsError,
    onApply,
  }: Props = $props();

  let tempCity = $state<'all' | 'HCM' | 'HN'>('all');
  let tempDistance = $state<'all' | '5' | '10'>('all');

  $effect(() => {
    tempCity = selectedCity;
    tempDistance = selectedDistance;
  });

  function handleApply() {
    onApply(tempCity, tempDistance);
    goBack();
  }
</script>

<div class="fullscreen-route-view filter-route">
  <!-- Top Navigation -->
  <div class="cartoon-card route-top-nav">
    <button type="button" class="btn btn-secondary back-btn" onclick={goBack}>
      ← Quay lại
    </button>
    <div class="nav-title-group">
      <h2><Icon name="filter" size={20} /> Tùy Chỉnh Bộ Lọc Tìm Kiếm</h2>
      <span class="sub-title">Chọn khu vực thành phố và bán kính vị trí</span>
    </div>
  </div>

  <!-- Compact Body Content -->
  <div class="cartoon-card filter-content-card">
    <!-- City Selection Row -->
    <div class="filter-section">
      <h3 class="section-title-label">
        <Icon name="building" size={16} /> Khu Vực:
      </h3>
      <div class="options-row">
        <button 
          type="button" 
          class="option-chip-btn {tempCity === 'all' ? 'active' : ''}"
          onclick={() => tempCity = 'all'}
        >
          <Icon name="map" size={15} />
          <span>Tất Cả</span>
        </button>

        <button 
          type="button" 
          class="option-chip-btn {tempCity === 'HCM' ? 'active' : ''}"
          onclick={() => tempCity = 'HCM'}
        >
          <Icon name="building" size={15} />
          <span>Hồ Chí Minh</span>
        </button>

        <button 
          type="button" 
          class="option-chip-btn {tempCity === 'HN' ? 'active' : ''}"
          onclick={() => tempCity = 'HN'}
        >
          <Icon name="landmark" size={15} />
          <span>Hà Nội</span>
        </button>
      </div>
    </div>

    <!-- Distance Selection Row -->
    <div class="filter-section" style="margin-top: 20px;">
      <h3 class="section-title-label">
        <Icon name="gps" size={16} /> Bán Kính (GPS):
      </h3>
      <div class="options-row">
        <button 
          type="button" 
          class="option-chip-btn {tempDistance === 'all' ? 'active' : ''}"
          onclick={() => tempDistance = 'all'}
        >
          <Icon name="pin" size={15} />
          <span>Tất Cả</span>
        </button>

        <button 
          type="button" 
          class="option-chip-btn {tempDistance === '5' ? 'active' : ''}"
          disabled={userLat === null}
          onclick={() => tempDistance = '5'}
        >
          <Icon name="zap" size={15} />
          <span>&lt; 5 km</span>
        </button>

        <button 
          type="button" 
          class="option-chip-btn {tempDistance === '10' ? 'active' : ''}"
          disabled={userLat === null}
          onclick={() => tempDistance = '10'}
        >
          <Icon name="rocket" size={15} />
          <span>&lt; 10 km</span>
        </button>
      </div>

      {#if userLat === null}
        <p class="gps-warning-hint">
          <Icon name="alert-triangle" size={14} /> Cần bật vị trí (GPS) để xem bán kính theo km.
        </p>
      {/if}
    </div>

    <!-- GPS Status bar -->
    <div class="gps-status-pill">
      {#if isTrackingGPS}
        <span class="gps-dot pulsing"></span>
        <span class="gps-text">Đang lấy vị trí GPS...</span>
      {:else if userLat !== null}
        <span class="gps-dot success"></span>
        <span class="gps-text">Đã định vị thành công</span>
      {:else if gpsError}
        <span class="gps-dot warning"></span>
        <span class="gps-text">Chưa bật định vị GPS</span>
      {/if}
    </div>

    <div class="apply-action-bar">
      <button type="button" class="btn btn-primary btn-apply-full" onclick={handleApply}>
        <Icon name="check-circle" size={18} /> Áp Dụng Bộ Lọc
      </button>
    </div>
  </div>
</div>

<style>
  .fullscreen-route-view {
    width: 100%;
    display: flex;
    flex-direction: column;
    gap: 16px;
    padding-bottom: 40px;
    max-width: 580px;
    margin: 0 auto;
  }

  .route-top-nav {
    background-color: var(--pastel-yellow);
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 12px 16px;
    border-radius: var(--radius-lg);
    box-shadow: 3px 3px 0 var(--color-border);
    text-align: left;
  }

  .back-btn {
    padding: 6px 12px !important;
    font-size: 0.88rem !important;
    white-space: nowrap;
  }

  .nav-title-group h2 {
    font-size: 1.1rem;
    font-weight: 800;
    margin: 0;
    display: flex;
    align-items: center;
    gap: 6px;
  }

  .sub-title {
    font-size: 0.8rem;
    font-weight: 600;
    color: var(--text-dark);
  }

  .filter-content-card {
    background-color: #fffefb;
    padding: 24px 20px;
    text-align: left;
  }

  .section-title-label {
    font-size: 0.95rem;
    font-weight: 800;
    margin-bottom: 10px;
    color: var(--text-dark);
    display: flex;
    align-items: center;
    gap: 6px;
  }

  /* Compact Horizontal Options Row */
  .options-row {
    display: flex;
    gap: 8px;
    width: 100%;
  }

  .option-chip-btn {
    flex: 1;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 6px;
    padding: 10px 8px;
    border-radius: var(--radius-md);
    border: var(--border-width) solid var(--color-border);
    background-color: #fff;
    cursor: pointer;
    box-shadow: 2.5px 2.5px 0 var(--color-border);
    font-family: var(--font-family);
    font-size: 0.88rem;
    font-weight: 800;
    white-space: nowrap;
    transition: all 0.1s ease;
  }

  .option-chip-btn:hover:not(:disabled) {
    transform: translate(-1px, -1px);
    box-shadow: 3.5px 3.5px 0 var(--color-border);
  }

  .option-chip-btn:active:not(:disabled) {
    transform: translate(1px, 1px);
    box-shadow: 1px 1px 0 var(--color-border);
  }

  .option-chip-btn.active {
    background-color: var(--pastel-yellow);
    box-shadow: 2.5px 2.5px 0 var(--color-border);
  }

  .option-chip-btn:disabled {
    background-color: #f3f4f6;
    color: #9ca3af;
    border-color: #d1d5db;
    cursor: not-allowed;
    box-shadow: 1.5px 1.5px 0 #d1d5db;
  }

  .gps-warning-hint {
    font-size: 0.8rem;
    font-weight: 700;
    color: #dc2626;
    margin-top: 8px;
    display: flex;
    align-items: center;
    gap: 6px;
  }

  .gps-status-pill {
    margin-top: 20px;
    padding: 10px 14px;
    background-color: var(--bg-secondary);
    border: var(--border-width-sm) solid var(--color-border);
    border-radius: var(--radius-md);
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .gps-dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    border: 1px solid var(--color-border);
  }

  .gps-dot.pulsing { background-color: #eab308; animation: pulse 1s infinite; }
  .gps-dot.success { background-color: #10b981; }
  .gps-dot.warning { background-color: #ef4444; }

  .gps-text {
    font-size: 0.82rem;
    font-weight: 700;
    color: var(--text-dark);
  }

  .apply-action-bar {
    margin-top: 20px;
  }

  .btn-apply-full {
    width: 100%;
    padding: 12px !important;
    font-size: 0.98rem !important;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 6px;
  }
</style>

// src/routes/FilterRoute.tsx
import React, { useState, useEffect } from "react";
import { goBack } from "../libs/router";
import Icon from "../components/Icon";

interface Props {
  selectedCity: "all" | "HCM" | "HN";
  selectedDistance: "all" | "5" | "10";
  userLat: number | null;
  isTrackingGPS: boolean;
  gpsError: boolean;
  onApply: (city: "all" | "HCM" | "HN", distance: "all" | "5" | "10") => void;
}

export default function FilterRoute({
  selectedCity = "all",
  selectedDistance = "all",
  userLat,
  isTrackingGPS,
  gpsError,
  onApply,
}: Props) {
  const [tempCity, setTempCity] = useState<"all" | "HCM" | "HN">(selectedCity);
  const [tempDistance, setTempDistance] = useState<"all" | "5" | "10">(selectedDistance);

  useEffect(() => {
    setTempCity(selectedCity);
    setTempDistance(selectedDistance);
  }, [selectedCity, selectedDistance]);

  function handleApply() {
    onApply(tempCity, tempDistance);
    goBack();
  }

  return (
    <div className="fullscreen-route-view filter-route w-full flex flex-col gap-4 pb-10 max-w-[580px] mx-auto">
      {/* Top Navigation */}
      <div className="cartoon-card route-top-nav bg-pastelYellow flex items-center gap-3 p-3 rounded-lg shadow-neo text-left">
        <button type="button" className="btn btn-secondary back-btn py-1.5 px-3 text-xs whitespace-nowrap" onClick={goBack}>
          ← Quay lại
        </button>
        <div className="nav-title-group">
          <h2 className="text-lg font-bold flex items-center gap-1.5 m-0"><Icon name="filter" size={20} /> Tùy Chỉnh Bộ Lọc Tìm Kiếm</h2>
          <span className="sub-title text-xs font-semibold text-[#1e1e24]">Chọn khu vực thành phố và bán kính vị trí</span>
        </div>
      </div>

      {/* Compact Body Content */}
      <div className="cartoon-card filter-content-card bg-[#fffefb] p-6 text-left border-3 border-[#1e1e24] rounded-2xl shadow-neo">
        {/* City Selection Row */}
        <div className="filter-section">
          <h3 className="section-title-label text-sm font-bold mb-2.5 text-[#1e1e24] flex items-center gap-1.5">
            <Icon name="building" size={16} /> Khu Vực:
          </h3>
          <div className="options-row flex gap-2 w-full">
            <button
              type="button"
              className={`option-chip-btn flex-1 flex items-center justify-center gap-1.5 p-2.5 rounded-md border-3 border-[#1e1e24] bg-white cursor-pointer shadow-[2.5px_2.5px_0_#1e1e24] font-bold text-xs whitespace-nowrap transition-all duration-100 hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[3.5px_3.5px_0_#1e1e24] active:translate-x-[1px] active:translate-y-[1px] active:shadow-[1px_1px_0_#1e1e24] ${
                tempCity === "all" ? "bg-pastelYellow" : ""
              }`}
              onClick={() => setTempCity("all")}
            >
              <Icon name="map" size={15} />
              <span>Tất Cả</span>
            </button>

            <button
              type="button"
              className={`option-chip-btn flex-1 flex items-center justify-center gap-1.5 p-2.5 rounded-md border-3 border-[#1e1e24] bg-white cursor-pointer shadow-[2.5px_2.5px_0_#1e1e24] font-bold text-xs whitespace-nowrap transition-all duration-100 hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[3.5px_3.5px_0_#1e1e24] active:translate-x-[1px] active:translate-y-[1px] active:shadow-[1px_1px_0_#1e1e24] ${
                tempCity === "HCM" ? "bg-pastelYellow" : ""
              }`}
              onClick={() => setTempCity("HCM")}
            >
              <Icon name="building" size={15} />
              <span>Hồ Chí Minh</span>
            </button>

            <button
              type="button"
              className={`option-chip-btn flex-1 flex items-center justify-center gap-1.5 p-2.5 rounded-md border-3 border-[#1e1e24] bg-white cursor-pointer shadow-[2.5px_2.5px_0_#1e1e24] font-bold text-xs whitespace-nowrap transition-all duration-100 hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[3.5px_3.5px_0_#1e1e24] active:translate-x-[1px] active:translate-y-[1px] active:shadow-[1px_1px_0_#1e1e24] ${
                tempCity === "HN" ? "bg-pastelYellow" : ""
              }`}
              onClick={() => setTempCity("HN")}
            >
              <Icon name="landmark" size={15} />
              <span>Hà Nội</span>
            </button>
          </div>
        </div>

        {/* Distance Selection Row */}
        <div className="filter-section mt-5">
          <h3 className="section-title-label text-sm font-bold mb-2.5 text-[#1e1e24] flex items-center gap-1.5">
            <Icon name="target" size={16} /> Bán Kính (GPS):
          </h3>
          <div className="options-row flex gap-2 w-full">
            <button
              type="button"
              className={`option-chip-btn flex-1 flex items-center justify-center gap-1.5 p-2.5 rounded-md border-3 border-[#1e1e24] bg-white cursor-pointer shadow-[2.5px_2.5px_0_#1e1e24] font-bold text-xs whitespace-nowrap transition-all duration-100 hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[3.5px_3.5px_0_#1e1e24] active:translate-x-[1px] active:translate-y-[1px] active:shadow-[1px_1px_0_#1e1e24] ${
                tempDistance === "all" ? "bg-pastelYellow" : ""
              }`}
              onClick={() => setTempDistance("all")}
            >
              <Icon name="pin" size={15} />
              <span>Tất Cả</span>
            </button>

            <button
              type="button"
              className={`option-chip-btn flex-1 flex items-center justify-center gap-1.5 p-2.5 rounded-md border-3 border-[#1e1e24] bg-white cursor-pointer shadow-[2.5px_2.5px_0_#1e1e24] font-bold text-xs whitespace-nowrap transition-all duration-100 hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[3.5px_3.5px_0_#1e1e24] active:translate-x-[1px] active:translate-y-[1px] active:shadow-[1px_1px_0_#1e1e24] disabled:bg-gray-100 disabled:text-gray-400 disabled:border-gray-300 disabled:cursor-not-allowed disabled:shadow-[1.5px_1.5px_0_#d1d5db] ${
                tempDistance === "5" ? "bg-pastelYellow" : ""
              }`}
              disabled={userLat === null}
              onClick={() => setTempDistance("5")}
            >
              <Icon name="zap" size={15} />
              <span>&lt; 5 km</span>
            </button>

            <button
              type="button"
              className={`option-chip-btn flex-1 flex items-center justify-center gap-1.5 p-2.5 rounded-md border-3 border-[#1e1e24] bg-white cursor-pointer shadow-[2.5px_2.5px_0_#1e1e24] font-bold text-xs whitespace-nowrap transition-all duration-100 hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[3.5px_3.5px_0_#1e1e24] active:translate-x-[1px] active:translate-y-[1px] active:shadow-[1px_1px_0_#1e1e24] disabled:bg-gray-100 disabled:text-gray-400 disabled:border-gray-300 disabled:cursor-not-allowed disabled:shadow-[1.5px_1.5px_0_#d1d5db] ${
                tempDistance === "10" ? "bg-pastelYellow" : ""
              }`}
              disabled={userLat === null}
              onClick={() => setTempDistance("10")}
            >
              <Icon name="rocket" size={15} />
              <span>&lt; 10 km</span>
            </button>
          </div>

          {userLat === null && (
            <p className="gps-warning-hint text-xs font-bold text-[#dc2626] mt-2 flex items-center gap-1.5">
              <Icon name="alert-triangle" size={14} /> Cần bật vị trí (GPS) để xem bán kính theo km.
            </p>
          )}
        </div>

        {/* GPS Status bar */}
        <div className="gps-status-pill mt-5 p-2.5 bg-bgCream border-2 border-[#1e1e24] rounded-md flex items-center gap-2">
          {isTrackingGPS ? (
            <>
              <span className="gps-dot pulsing w-2 h-2 rounded-full border border-[#1e1e24] bg-[#eab308] animate-pulse"></span>
              <span className="gps-text text-xs font-bold text-[#1e1e24]">Đang lấy vị trí GPS...</span>
            </>
          ) : userLat !== null ? (
            <>
              <span className="gps-dot success w-2 h-2 rounded-full border border-[#1e1e24] bg-[#10b981]"></span>
              <span className="gps-text text-xs font-bold text-[#1e1e24]">Đã định vị thành công</span>
            </>
          ) : (
            <>
              <span className="gps-dot warning w-2 h-2 rounded-full border border-[#1e1e24] bg-[#ef4444]"></span>
              <span className="gps-text text-xs font-bold text-[#1e1e24]">Chưa bật định vị GPS</span>
            </>
          )}
        </div>

        <div className="apply-action-bar mt-5">
          <button type="button" className="btn btn-primary btn-apply-full w-full py-3 text-[0.98rem] flex items-center justify-center gap-1.5" onClick={handleApply}>
            <Icon name="check-circle" size={18} /> Áp Dụng Bộ Lọc
          </button>
        </div>
      </div>
    </div>
  );
}
