// src/routes/MyMeetupsRoute.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { onAuthStateChanged, type User } from "firebase/auth";
  import { auth } from "../lib/firebase";
  import MeetupList from "../lib/MeetupList.svelte";
  import Icon from "../lib/Icon.svelte";

  interface Meetup {
    id: string;
    title: string;
    game: string;
    host_name?: string;
    hostName?: string;
    host_uid?: string;
    hostUid?: string;
    lat: number;
    lng: number;
    players_count?: number;
    playersCount?: number;
    players_needed?: number;
    playersNeeded?: number;
    time: string;
    color: string;
    hostFcmToken?: string;
    pendingUids?: string[];
    approvedPendingUids?: string[];
    approvedUids?: string[];
  }

  interface Props {
    meetups: Meetup[];
    userLat: number | null;
    userLng: number | null;
    selectedCity: "all" | "HCM" | "HN";
    selectedDistance: "all" | "5" | "10";
    isTrackingGPS: boolean;
    gpsError: boolean;
    addToast: (msg: string, type: "success" | "error" | "info") => void;
    isLoading?: boolean;
  }

  let {
    meetups,
    userLat,
    userLng,
    selectedCity = $bindable("all"),
    selectedDistance = $bindable("all"),
    isTrackingGPS,
    gpsError,
    isLoading = false,
  }: Props = $props();

  let currentUser = $state<User | null>(auth.currentUser);
  let unsubscribeAuth: (() => void) | null = null;
  let activeTab = $state<"all" | "host" | "member" | "pending">("all");

  onMount(() => {
    unsubscribeAuth = onAuthStateChanged(auth, (user) => {
      currentUser = user;
    });
  });

  onDestroy(() => {
    if (unsubscribeAuth) unsubscribeAuth();
  });

  // Lọc danh sách kèo liên quan tới user hiện tại
  let myMeetups = $derived.by(() => {
    if (!currentUser) return [];
    const uid = currentUser.uid;

    return meetups.filter((m) => {
      const isUserHost = m.hostUid === uid || m.host_uid === uid;
      const isUserMember = Array.isArray(m.approvedUids) && m.approvedUids.includes(uid);
      const isUserPending = (Array.isArray(m.pendingUids) && m.pendingUids.includes(uid)) ||
                            (Array.isArray(m.approvedPendingUids) && m.approvedPendingUids.includes(uid));

      if (activeTab === "all") {
        return isUserHost || isUserMember || isUserPending;
      }
      if (activeTab === "host") {
        return isUserHost;
      }
      if (activeTab === "member") {
        return isUserMember && !isUserHost;
      }
      if (activeTab === "pending") {
        return isUserPending;
      }
      return false;
    });
  });
</script>

<section id="my-meetups-route">
  <h2 class="section-title">Các Kèo Của Bạn</h2>

  {#if currentUser}
    <!-- Tab Filter Bar (Neo-brutalist Style) -->
    <div class="cartoon-card my-meetups-filter">
      <span class="filter-label">Lọc kèo:</span>
      <div class="tab-btn-group">
        <button
          type="button"
          class="tab-btn-pill {activeTab === 'all' ? 'active' : ''}"
          onclick={() => activeTab = "all"}
        >
          <Icon name="dice" size={15} />
          <span>Tất cả kèo</span>
        </button>
        <button
          type="button"
          class="tab-btn-pill {activeTab === 'host' ? 'active' : ''}"
          onclick={() => activeTab = "host"}
        >
          <Icon name="crown" size={15} />
          <span>Tôi làm Host</span>
        </button>
        <button
          type="button"
          class="tab-btn-pill {activeTab === 'member' ? 'active' : ''}"
          onclick={() => activeTab = "member"}
        >
          <Icon name="check-circle" size={15} />
          <span>Đã tham gia</span>
        </button>
        <button
          type="button"
          class="tab-btn-pill {activeTab === 'pending' ? 'active' : ''}"
          onclick={() => activeTab = "pending"}
        >
          <Icon name="clock" size={15} />
          <span>Đang chờ duyệt</span>
        </button>
      </div>
    </div>

    <!-- Render filtered meetup cards -->
    <MeetupList
      meetups={myMeetups}
      {userLat}
      {userLng}
      bind:selectedCity
      bind:selectedDistance
      {isTrackingGPS}
      {gpsError}
      showFilterBar={false}
      {isLoading}
    />
  {:else}
    <!-- Unauthorized warning -->
    <div class="cartoon-card locked-card">
      <div class="locked-icon">
        <Icon name="lock" size={40} />
      </div>
      <h4 class="locked-title">Cần Đăng Nhập Tài Khoản</h4>
      <p class="locked-description">
        Bạn cần đăng nhập để xem danh sách các kèo chơi boardgame mà bạn làm host hoặc đã đăng ký tham gia chơi!
      </p>
      <a
        href="#/profile"
        class="btn btn-primary login-link-btn"
      >
        <Icon name="key" size={16} />
        <span>Đi tới trang Đăng nhập</span>
      </a>
    </div>
  {/if}
</section>

<style>
  #my-meetups-route {
    padding-bottom: 60px;
  }

  /* Tab Filter Bar */
  .my-meetups-filter {
    margin-bottom: 24px;
    padding: 15px;
    background-color: #fffefb;
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
    justify-content: center;
    align-items: center;
  }

  .filter-label {
    font-weight: 800;
    font-size: 0.95rem;
    margin-right: 8px;
    color: var(--text-dark);
  }

  .tab-btn-group {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
  }

  /* Neo-brutalist pill buttons */
  .tab-btn-pill {
    padding: 8px 16px;
    font-size: 0.85rem;
    font-weight: 700;
    font-family: var(--font-family);
    border: 3px solid #1e1e24;
    border-radius: 100px;
    cursor: pointer;
    transition: transform 0.1s ease, box-shadow 0.1s ease;
    outline: none;
    background-color: #ffffff;
    box-shadow: 3px 3px 0px #1e1e24;
  }

  .tab-btn-pill.active {
    background-color: var(--pastel-yellow, #ffe869);
    box-shadow: 2px 2px 0px #1e1e24;
    transform: translate(1px, 1px);
  }

  .tab-btn-pill:hover {
    transform: translate(-1px, -1px);
    box-shadow: 4px 4px 0px #1e1e24;
  }

  .tab-btn-pill.active:hover {
    transform: translate(1px, 1px);
    box-shadow: 2px 2px 0px #1e1e24;
  }

  .tab-btn-pill:active {
    transform: translate(3px, 3px);
    box-shadow: 0px 0px 0px #1e1e24;
  }

  /* Locked State */
  .locked-card {
    padding: 40px;
    background-color: #fffefb;
    text-align: center;
    margin-top: 20px;
  }

  .locked-icon {
    font-size: 3rem;
    display: block;
    margin-bottom: 16px;
  }

  .locked-title {
    font-size: 1.3rem;
    font-weight: 700;
    margin-bottom: 8px;
    color: var(--text-dark);
  }

  .locked-description {
    font-size: 0.95rem;
    font-weight: 500;
    color: var(--text-muted);
    max-width: 360px;
    margin: 0 auto 24px auto;
    line-height: 1.5;
  }

  .login-link-btn {
    display: inline-block;
    padding: 12px 28px;
    font-size: 0.95rem;
    font-weight: 800;
    border: 3px solid #1e1e24;
    border-radius: 8px;
    background-color: var(--pastel-yellow, #ffe869);
    color: #1e1e24;
    box-shadow: 4px 4px 0px #1e1e24;
    text-decoration: none;
  }
</style>

// src/routes/MyMeetupsRoute.tsx
import React, { useState, useEffect } from "react";
import { onAuthStateChanged, type User } from "firebase/auth";
import { auth } from "../libs/firebase";
import MeetupList from "../components/MeetupList";
import Icon from "../components/Icon";

interface Meetup {
  id: string;
  title: string;
  game: string;
  host_name?: string;
  hostName?: string;
  host_uid?: string;
  hostUid?: string;
  lat: number;
  lng: number;
  players_count?: number;
  playersCount?: number;
  players_needed?: number;
  playersNeeded?: number;
  time: string;
  color: string;
  hostFcmToken?: string;
  pendingUids?: string[];
  approvedPendingUids?: string[];
  approvedUids?: string[];
}

interface Props {
  meetups: Meetup[];
  userLat: number | null;
  userLng: number | null;
  selectedCity: "all" | "HCM" | "HN";
  selectedDistance: "all" | "5" | "10";
  isTrackingGPS: boolean;
  gpsError: boolean;
  isLoading?: boolean;
}

export default function MyMeetupsRoute({
  meetups,
  userLat,
  userLng,
  selectedCity = "all",
  selectedDistance = "all",
  isTrackingGPS,
  gpsError,
  isLoading = false,
}: Props) {
  const [currentUser, setCurrentUser] = useState<User | null>(auth.currentUser);
  const [activeTab, setActiveTab] = useState<"all" | "host" | "member" | "pending">("all");

  useEffect(() => {
    const unsub = onAuthStateChanged(auth, (user) => {
      setCurrentUser(user);
    });
    return unsub;
  }, []);

  // Filter meetups related to current user
  const myMeetups = currentUser
    ? meetups.filter((m) => {
        const uid = currentUser.uid;
        const isUserHost = m.hostUid === uid || m.host_uid === uid;
        const isUserMember = Array.isArray(m.approvedUids) && m.approvedUids.includes(uid);
        const isUserPending =
          (Array.isArray(m.pendingUids) && m.pendingUids.includes(uid)) ||
          (Array.isArray(m.approvedPendingUids) && m.approvedPendingUids.includes(uid));

        if (activeTab === "all") {
          return isUserHost || isUserMember || isUserPending;
        }
        if (activeTab === "host") {
          return isUserHost;
        }
        if (activeTab === "member") {
          return isUserMember && !isUserHost;
        }
        if (activeTab === "pending") {
          return isUserPending;
        }
        return false;
      })
    : [];

  return (
    <section id="my-meetups-route" className="pb-[60px]">
      <h2 className="section-title">Các Kèo Của Bạn</h2>

      {currentUser ? (
        <>
          {/* Tab Filter Bar (Neo-brutalist Style) */}
          <div className="cartoon-card my-meetups-filter mb-6 p-[15px] bg-[#fffefb] flex flex-wrap gap-2.5 justify-center items-center">
            <span className="filter-label font-extrabold text-[0.95rem] mr-2 text-[#1e1e24]">Lọc kèo:</span>
            <div className="tab-btn-group flex flex-wrap gap-2">
              <button
                type="button"
                className={`tab-btn-pill py-2 px-4 text-[0.85rem] font-bold border-3 border-[#1e1e24] rounded-full cursor-pointer transition-all duration-100 outline-none bg-white shadow-[3px_3px_0_#1e1e24] hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[4px_4px_0_#1e1e24] active:translate-x-[3px] active:translate-y-[3px] active:shadow-none ${
                  activeTab === "all" ? "bg-pastelYellow shadow-[2px_2px_0_#1e1e24] translate-x-[1px] translate-y-[1px]" : ""
                }`}
                onClick={() => setActiveTab("all")}
              >
                <Icon name="dice" size={15} className="mr-1 inline" />
                <span>Tất cả kèo</span>
              </button>
              <button
                type="button"
                className={`tab-btn-pill py-2 px-4 text-[0.85rem] font-bold border-3 border-[#1e1e24] rounded-full cursor-pointer transition-all duration-100 outline-none bg-white shadow-[3px_3px_0_#1e1e24] hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[4px_4px_0_#1e1e24] active:translate-x-[3px] active:translate-y-[3px] active:shadow-none ${
                  activeTab === "host" ? "bg-pastelYellow shadow-[2px_2px_0_#1e1e24] translate-x-[1px] translate-y-[1px]" : ""
                }`}
                onClick={() => setActiveTab("host")}
              >
                <Icon name="crown" size={15} className="mr-1 inline" />
                <span>Tôi làm Host</span>
              </button>
              <button
                type="button"
                className={`tab-btn-pill py-2 px-4 text-[0.85rem] font-bold border-3 border-[#1e1e24] rounded-full cursor-pointer transition-all duration-100 outline-none bg-white shadow-[3px_3px_0_#1e1e24] hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[4px_4px_0_#1e1e24] active:translate-x-[3px] active:translate-y-[3px] active:shadow-none ${
                  activeTab === "member" ? "bg-pastelYellow shadow-[2px_2px_0_#1e1e24] translate-x-[1px] translate-y-[1px]" : ""
                }`}
                onClick={() => setActiveTab("member")}
              >
                <Icon name="check-circle" size={15} className="mr-1 inline" />
                <span>Đã tham gia</span>
              </button>
              <button
                type="button"
                className={`tab-btn-pill py-2 px-4 text-[0.85rem] font-bold border-3 border-[#1e1e24] rounded-full cursor-pointer transition-all duration-100 outline-none bg-white shadow-[3px_3px_0_#1e1e24] hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[4px_4px_0_#1e1e24] active:translate-x-[3px] active:translate-y-[3px] active:shadow-none ${
                  activeTab === "pending" ? "bg-pastelYellow shadow-[2px_2px_0_#1e1e24] translate-x-[1px] translate-y-[1px]" : ""
                }`}
                onClick={() => setActiveTab("pending")}
              >
                <Icon name="clock" size={15} className="mr-1 inline" />
                <span>Đang chờ duyệt</span>
              </button>
            </div>
          </div>

          {/* Render filtered meetup cards */}
          <MeetupList
            meetups={myMeetups}
            userLat={userLat}
            userLng={userLng}
            selectedCity={selectedCity}
            selectedDistance={selectedDistance}
            isTrackingGPS={isTrackingGPS}
            gpsError={gpsError}
            showFilterBar={false}
            isLoading={isLoading}
          />
        </>
      ) : (
        <div className="cartoon-card locked-card p-10 bg-[#fffefb] text-center mt-5 border-3 border-[#1e1e24] shadow-neo rounded-2xl">
          <div className="locked-icon flex justify-center items-center mb-4 text-[#1e1e24]">
            <Icon name="lock" size={40} />
          </div>
          <h4 className="locked-title text-xl font-bold mb-2 text-[#1e1e24]">Cần Đăng Nhập Tài Khoản</h4>
          <p className="locked-description text-[0.95rem] font-semibold text-[#666666] max-w-[360px] mx-auto mb-6 leading-relaxed">
            Bạn cần đăng nhập để xem danh sách các kèo chơi boardgame mà bạn làm host hoặc đã đăng ký tham gia chơi!
          </p>
          <a href="#/profile" className="login-link-btn inline-flex items-center gap-2 py-3 px-7 text-[0.95rem] font-extrabold border-3 border-[#1e1e24] rounded-lg bg-pastelYellow text-[#1e1e24] shadow-neo no-underline">
            <Icon name="key" size={16} />
            <span>Đi tới trang Đăng nhập</span>
          </a>
        </div>
      )}
    </section>
  );
}
