// src/lib/ChatView.svelte
<script lang="ts">
  import { onMount, onDestroy, tick } from 'svelte';
  import { 
    collection, 
    addDoc, 
    query, 
    orderBy, 
    onSnapshot, 
    serverTimestamp,
    type Unsubscribe
  } from 'firebase/firestore';
  import { onAuthStateChanged, type User } from 'firebase/auth';
  import { db, auth } from './firebase';
  import Icon from './Icon.svelte';

  import { 
    isApprovedMember, 
    requestToJoin, 
    cancelJoinRequest, 
    subscribeToMeetupRequests,
    type MeetupRequest
  } from './meetupService';
  import { notifyMeetupChatMembers } from './notificationService';

  interface Meetup {
    id: string;
    title: string;
    game: string;
    host_name?: string;
    hostName?: string;
    host_uid?: string;
    hostUid?: string;
    approvedUids?: string[];
    color?: string;
  }

  interface ChatMessage {
    id: string;
    text: string;
    senderUid: string;
    senderName: string;
    createdAt?: any;
  }

  interface Props {
    meetup: Meetup | null;
    onBack: () => void;
  }

  let { meetup, onBack }: Props = $props();

  let messages = $state<ChatMessage[]>([]);
  let requests = $state<MeetupRequest[]>([]);
  let newMessageText = $state<string>('');
  let isSending = $state<boolean>(false);
  let isRequesting = $state<boolean>(false);
  let currentUser = $state<User | null>(auth.currentUser);
  let messagesContainer = $state<HTMLElement | null>(null);
  let unsubscribeStore: Unsubscribe | null = null;
  let unsubscribeAuth: Unsubscribe | null = null;
  let unsubscribeReqs: Unsubscribe | null = null;

  let hasChatAccess = $derived(isApprovedMember(meetup, currentUser?.uid));
  
  let myRequest = $derived.by(() => {
    if (!currentUser || !requests.length) return null;
    return requests.find(r => r.uid === currentUser?.uid) || null;
  });


  onMount(() => {
    unsubscribeAuth = onAuthStateChanged(auth, (user) => {
      currentUser = user;
    });

    if (meetup?.id) {
      subscribeToMessages(meetup.id);
    }
  });

  onDestroy(() => {
    if (unsubscribeAuth) unsubscribeAuth();
    if (unsubscribeStore) unsubscribeStore();
  });

  $effect(() => {
    if (meetup?.id) {
      subscribeToMessages(meetup.id);
    }
  });

  function subscribeToMessages(meetupId: string) {
    if (unsubscribeStore) unsubscribeStore();

    const messagesRef = collection(db, 'meetups', meetupId, 'messages');
    const q = query(messagesRef, orderBy('createdAt', 'asc'));

    unsubscribeStore = onSnapshot(q, (snapshot) => {
      messages = snapshot.docs.map((doc) => ({
        id: doc.id,
        ...doc.data()
      })) as ChatMessage[];

      tick().then(() => {
        if (messagesContainer) {
          messagesContainer.scrollTop = messagesContainer.scrollHeight;
        }
      });
    }, (error) => {
      console.error('[Firestore Chat] Subscription error:', error);
    });
  }

  async function handleSendMessage(e?: Event) {
    if (e) e.preventDefault();
    if (!newMessageText.trim() || !meetup?.id || !currentUser || isSending) return;

    const text = newMessageText.trim();
    newMessageText = '';
    isSending = true;

    try {
      const senderName = currentUser.displayName || currentUser.email || 'Thành viên';
      await addDoc(collection(db, 'meetups', meetup.id, 'messages'), {
        text,
        senderUid: currentUser.uid,
        senderName,
        createdAt: serverTimestamp()
      });

      const allMembers = [
        ...(meetup.approvedUids || []),
        meetup.hostUid || meetup.host_uid || ''
      ].filter(Boolean);

      // Trigger push notification to other participating members asynchronously
      notifyMeetupChatMembers(
        meetup.id,
        meetup.title,
        allMembers,
        currentUser.uid,
        senderName,
        text
      );
    } catch (err) {
      console.error('[Firestore Chat] Send error:', err);
    } finally {
      isSending = false;
    }
  }

  async function handleSendJoinRequest() {
    if (!meetup?.id || !currentUser || isRequesting) return;
    isRequesting = true;
    try {
      await requestToJoin(meetup.id, currentUser);
    } catch (err) {
      console.error('Request join failed:', err);
    } finally {
      isRequesting = false;
    }
  }

  async function handleCancelRequest() {
    if (!meetup?.id || !currentUser || isRequesting) return;
    isRequesting = true;
    try {
      await cancelJoinRequest(meetup.id, currentUser.uid);
    } catch (err) {
      console.error('Cancel request failed:', err);
    } finally {
      isRequesting = false;
    }
  }

  function formatMessageTime(timestamp: any): string {
    if (!timestamp) return 'Vừa xong';
    try {
      const date = timestamp.toDate ? timestamp.toDate() : new Date(timestamp);
      return date.toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' });
    } catch {
      return 'Vừa xong';
    }
  }
</script>

<div class="fullscreen-chat-view">
  {#if !meetup}
    <div class="cartoon-card no-chat-card">
      <h3>Chưa chọn kèo chơi nào!</h3>
      <button class="btn btn-primary" onclick={onBack}>Quay lại danh sách kèo</button>
    </div>
  {:else if !hasChatAccess}
    <!-- Top Fullscreen Header -->
    <div class="chat-top-nav cartoon-card">
      <button type="button" class="btn btn-secondary back-btn" onclick={onBack}>
        ← Quay lại
      </button>

      <div class="chat-nav-details">
        <div class="chat-title-row">
          <h2 class="chat-meetup-title">{meetup.title}</h2>
          <span class="game-badge"><Icon name="dice" size={13} class="inline-icon" /> {meetup.game}</span>
        </div>
        <span class="host-info">
          <Icon name="crown" size={13} class="inline-icon" /> Host: <strong>{meetup.host_name || meetup.hostName || 'Ẩn danh'}</strong>
        </span>
      </div>
    </div>

    <!-- Access Denied Private Lock Screen -->
    <div class="cartoon-card access-denied-card">
      <div class="lock-big-icon"><Icon name="lock" size={48} /></div>
      <h3>Phòng Chat Riêng Tư</h3>
      <p>Chỉ những người chơi đã được Host phê duyệt vào kèo mới có quyền xem và nhắn tin trong phòng chat này.</p>

      <div class="access-action-box">
        {#if !currentUser}
          <p class="prompt-text"><Icon name="sparkles" size={16} class="inline-icon" /> Hãy đăng nhập ở tab <strong>Hồ sơ</strong> để gửi yêu cầu tham gia kèo.</p>
          <button class="btn btn-primary" onclick={onBack}>Quay lại danh sách kèo</button>
        {:else if myRequest?.status === 'pending'}
          <div class="pending-status-pill">
            <Icon name="clock" size={16} class="inline-icon" /> Yêu cầu của bạn đang chờ Host xét duyệt...
          </div>
          <div class="action-btn-group">
            <button class="btn btn-secondary" onclick={handleCancelRequest} disabled={isRequesting}>
              <Icon name="x" size={15} class="inline-icon" />
              <span>{isRequesting ? '...' : 'Hủy yêu cầu'}</span>
            </button>
            <button class="btn btn-primary" onclick={onBack}>Quay lại danh sách</button>
          </div>
        {:else}
          <div class="action-btn-group">
            <button class="btn btn-success" onclick={handleSendJoinRequest} disabled={isRequesting}>
              <Icon name="handshake" size={15} class="inline-icon" />
              <span>{isRequesting ? 'Đang gửi...' : 'Gửi yêu cầu tham gia kèo'}</span>
            </button>
            <button class="btn btn-primary" onclick={onBack}>Quay lại danh sách</button>
          </div>
        {/if}
      </div>
    </div>
  {:else}
    <!-- Top Fullscreen Header -->
    <div class="chat-top-nav cartoon-card">
      <button type="button" class="btn btn-secondary back-btn" onclick={onBack}>
        ← Quay lại
      </button>

      <div class="chat-nav-details">
        <div class="chat-title-row">
          <h2 class="chat-meetup-title">{meetup.title}</h2>
          <span class="game-badge"><Icon name="dice" size={13} class="inline-icon" /> {meetup.game}</span>
        </div>
        <span class="host-info">
          <Icon name="crown" size={13} class="inline-icon" /> Host: <strong>{meetup.host_name || meetup.hostName || 'Ẩn danh'}</strong>
        </span>
      </div>
    </div>

    <!-- Messages Container Area -->

    <div class="chat-feed-area cartoon-card" bind:this={messagesContainer}>
      {#if messages.length === 0}
        <div class="chat-empty-state">
          <div class="empty-icon"><Icon name="chat" size={48} /></div>
          <h3>Chưa có tin nhắn nào trong kèo này!</h3>
          <p>Hãy mở lời gửi tin nhắn đầu tiên để thảo luận và hẹn giờ chơi cùng mọi người nhé.</p>
        </div>
      {:else}
        <div class="messages-list">
          {#each messages as msg (msg.id)}
            {@const isMine = currentUser && msg.senderUid === currentUser.uid}
            {@const isHost = (meetup.host_uid || meetup.hostUid) === msg.senderUid}

            <div class="message-row {isMine ? 'my-message-row' : 'other-message-row'}">
              <div class="message-bubble {isMine ? 'my-bubble' : 'other-bubble'}">
                <div class="message-author">
                  <span class="author-name">{msg.senderName}</span>
                  {#if isHost}
                    <span class="host-badge"><Icon name="crown" size={11} /> Host</span>
                  {/if}
                </div>
                <div class="message-text">{msg.text}</div>
                <div class="message-time">{formatMessageTime(msg.createdAt)}</div>
              </div>
            </div>
          {/each}
        </div>
      {/if}
    </div>

    <!-- Bottom Fullscreen Input Bar -->
    <div class="chat-bottom-bar cartoon-card">
      {#if currentUser}
        <form class="chat-input-form" onsubmit={handleSendMessage}>
          <input 
            type="text" 
            class="cartoon-chat-input" 
            placeholder="Nhập tin nhắn..." 
            bind:value={newMessageText}
            disabled={isSending}
          />
          <button 
            type="submit" 
            class="btn btn-primary send-btn" 
            disabled={!newMessageText.trim() || isSending}
          >
            <Icon name="rocket" size={16} class="inline-icon" />
            <span>{isSending ? '...' : 'Gửi'}</span>
          </button>
        </form>
      {:else}
        <div class="login-chat-prompt">
          <span><Icon name="lock" size={14} class="inline-icon" /> Bạn cần đăng nhập ở tab <strong>Hồ sơ</strong> để gửi tin nhắn chat.</span>
        </div>
      {/if}
    </div>
  {/if}
</div>

<style>
  .fullscreen-chat-view {
    width: 100%;
    display: flex;
    flex-direction: column;
    height: calc(100vh - 120px);
    gap: 16px;
    margin-bottom: 20px;
  }

  @media (max-width: 768px) {
    .fullscreen-chat-view {
      height: calc(100vh - 160px);
    }
  }

  .no-chat-card {
    margin: auto;
    text-align: center;
    padding: 40px;
    background-color: #fff;
  }

  .access-denied-card {
    margin: auto;
    text-align: center;
    padding: 40px 24px;
    background-color: #fffefb;
    max-width: 480px;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 16px;
  }

  .lock-big-icon {
    font-size: 3.5rem;
    display: block;
  }

  .access-denied-card h3 {
    font-size: 1.5rem;
    margin: 0;
  }

  .access-denied-card p {
    font-size: 0.95rem;
    font-weight: 600;
    color: var(--text-muted);
    line-height: 1.5;
    margin: 0;
  }

  .access-action-box {
    margin-top: 12px;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 14px;
    width: 100%;
  }

  .action-btn-group {
    display: flex;
    gap: 12px;
    width: 100%;
    justify-content: center;
  }

  .action-btn-group .btn {
    flex: 1;
  }

  .pending-status-pill {
    padding: 10px 16px;
    background-color: var(--pastel-yellow);
    border: var(--border-width) solid var(--color-border);
    border-radius: var(--radius-md);
    font-weight: 800;
    font-size: 0.9rem;
    box-shadow: 3px 3px 0 var(--color-border);
  }


  .no-chat-card h3 {
    margin-bottom: 16px;
  }

  /* Top Navigation Bar */
  .chat-top-nav {
    background-color: var(--pastel-cyan);
    display: flex;
    align-items: center;
    gap: 16px;
    padding: 14px 20px;
    border-radius: var(--radius-lg);
    box-shadow: 4px 4px 0 var(--color-border);
    flex-shrink: 0;
  }

  .back-btn {
    padding: 8px 16px !important;
    font-size: 0.95rem !important;
    white-space: nowrap;
  }

  .chat-nav-details {
    display: flex;
    flex-direction: column;
    gap: 2px;
    text-align: left;
    flex: 1;
    min-width: 0;
  }

  .chat-title-row {
    display: flex;
    align-items: center;
    gap: 10px;
    flex-wrap: wrap;
  }

  .chat-meetup-title {
    font-size: 1.3rem;
    font-weight: 800;
    margin: 0;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    color: var(--text-dark);
  }

  .game-badge {
    font-size: 0.82rem;
    font-weight: 800;
    background-color: var(--pastel-yellow);
    padding: 2px 10px;
    border: var(--border-width-sm) solid var(--color-border);
    border-radius: var(--radius-sm);
    box-shadow: 1.5px 1.5px 0 var(--color-border);
  }

  .host-info {
    font-size: 0.85rem;
    font-weight: 600;
    color: var(--text-dark);
  }

  /* Chat Feed Messages Area */
  .chat-feed-area {
    flex: 1;
    background-color: var(--bg-primary);
    overflow-y: auto;
    padding: 20px;
    display: flex;
    flex-direction: column;
    border-radius: var(--radius-lg);
    box-shadow: 4px 4px 0 var(--color-border);
  }

  .chat-empty-state {
    margin: auto;
    text-align: center;
    padding: 40px 20px;
    color: var(--text-muted);
  }

  .empty-icon {
    font-size: 3.5rem;
    display: block;
    margin-bottom: 12px;
  }

  .chat-empty-state h3 {
    font-size: 1.3rem;
    margin-bottom: 8px;
    color: var(--text-dark);
  }

  .chat-empty-state p {
    font-size: 0.95rem;
    font-weight: 600;
    max-width: 360px;
    margin: 0 auto;
  }

  .messages-list {
    display: flex;
    flex-direction: column;
    gap: 16px;
    width: 100%;
  }

  .message-row {
    display: flex;
    width: 100%;
  }

  .my-message-row {
    justify-content: flex-end;
  }

  .other-message-row {
    justify-content: flex-start;
  }

  .message-bubble {
    max-width: 75%;
    padding: 12px 16px;
    border-radius: 20px;
    border: var(--border-width) solid var(--color-border);
    box-shadow: 4px 4px 0 var(--color-border);
    text-align: left;
    display: flex;
    flex-direction: column;
    gap: 4px;
    animation: bubble-pop 0.15s cubic-bezier(0.175, 0.885, 0.32, 1.25);
  }

  @keyframes bubble-pop {
    from { transform: scale(0.9); opacity: 0; }
    to { transform: scale(1); opacity: 1; }
  }

  .my-bubble {
    background-color: var(--pastel-purple);
    border-bottom-right-radius: 4px;
  }

  .other-bubble {
    background-color: #fff;
    border-bottom-left-radius: 4px;
  }

  .message-author {
    display: flex;
    align-items: center;
    gap: 6px;
  }

  .author-name {
    font-size: 0.82rem;
    font-weight: 800;
    color: var(--text-dark);
  }

  .host-badge {
    font-size: 0.7rem;
    font-weight: 800;
    background-color: var(--pastel-yellow);
    border: 1.5px solid var(--color-border);
    padding: 1px 6px;
    border-radius: 100px;
  }

  .message-text {
    font-size: 1rem;
    font-weight: 600;
    color: var(--text-dark);
    word-break: break-word;
    line-height: 1.4;
  }

  .message-time {
    font-size: 0.72rem;
    font-weight: 700;
    color: var(--text-muted);
    align-self: flex-end;
  }

  /* Bottom Input Bar */
  .chat-bottom-bar {
    background-color: #fff;
    padding: 14px 20px;
    border-radius: var(--radius-lg);
    box-shadow: 4px 4px 0 var(--color-border);
    flex-shrink: 0;
  }

  .chat-input-form {
    display: flex;
    width: 100%;
    gap: 12px;
  }

  .cartoon-chat-input {
    flex: 1;
    padding: 12px 16px;
    font-family: var(--font-family);
    font-size: 1rem;
    font-weight: 600;
    border-radius: var(--radius-md);
    border: var(--border-width) solid var(--color-border);
    background-color: var(--bg-secondary);
    outline: none;
    box-shadow: 3px 3px 0 var(--color-border);
    transition: all 0.15s ease;
  }

  .cartoon-chat-input:focus {
    background-color: #fff;
    box-shadow: 4px 4px 0 var(--color-border);
  }

  .send-btn {
    padding: 12px 24px !important;
    font-size: 1rem !important;
    white-space: nowrap;
  }

  .login-chat-prompt {
    width: 100%;
    text-align: center;
    font-size: 0.9rem;
    font-weight: 700;
    color: var(--text-muted);
    padding: 6px 0;
  }
</style>

// src/components/ChatView.tsx
import React, { useState, useEffect, useRef } from "react";
import {
  collection,
  addDoc,
  query,
  orderBy,
  onSnapshot,
  serverTimestamp,
} from "firebase/firestore";
import { onAuthStateChanged, type User } from "firebase/auth";
import { db, auth } from "../libs/firebase";
import Icon from "./Icon";

import {
  isApprovedMember,
  requestToJoin,
  cancelJoinRequest,
  subscribeToMeetupRequests,
  type MeetupRequest,
} from "../api/meetupService";
import { notifyMeetupChatMembers } from "../api/notificationService";
import { formatMessageTime } from "../utils/time";

interface Meetup {
  id: string;
  title: string;
  game: string;
  host_name?: string;
  hostName?: string;
  host_uid?: string;
  hostUid?: string;
  approvedUids?: string[];
  color?: string;
}

interface ChatMessage {
  id: string;
  text: string;
  senderUid: string;
  senderName: string;
  createdAt?: any;
}

interface Props {
  meetup: Meetup | null;
  onBack: () => void;
}

export default function ChatView({ meetup, onBack }: Props) {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [requests, setRequests] = useState<MeetupRequest[]>([]);
  const [newMessageText, setNewMessageText] = useState<string>("");
  const [isSending, setIsSending] = useState<boolean>(false);
  const [isRequesting, setIsRequesting] = useState<boolean>(false);
  const [currentUser, setCurrentUser] = useState<User | null>(auth.currentUser);

  const messagesContainerRef = useRef<HTMLDivElement | null>(null);
  const messagesEndRef = useRef<HTMLDivElement | null>(null);

  const hasChatAccess = isApprovedMember(meetup, currentUser?.uid);

  const myRequest = currentUser
    ? requests.find((r) => r.uid === currentUser.uid) || null
    : null;

  // Listen to Auth State Changes
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      setCurrentUser(user);
    });
    return unsubscribe;
  }, []);

  // Listen to Meetup Requests (For access control checking)
  useEffect(() => {
    if (meetup?.id && currentUser) {
      const unsubscribe = subscribeToMeetupRequests(meetup.id, (list) => {
        setRequests(list);
      });
      return unsubscribe;
    } else {
      setRequests([]);
    }
  }, [meetup?.id, currentUser]);

  // Listen to Chat Messages
  useEffect(() => {
    if (!meetup?.id || !hasChatAccess) {
      setMessages([]);
      return;
    }

    const messagesRef = collection(db, "meetups", meetup.id, "messages");
    const q = query(messagesRef, orderBy("createdAt", "asc"));

    const unsubscribe = onSnapshot(
      q,
      (snapshot) => {
        const list = snapshot.docs.map((doc) => ({
          id: doc.id,
          ...doc.data(),
        })) as ChatMessage[];
        setMessages(list);
      },
      (error) => {
        console.error("[Firestore Chat] Subscription error:", error);
      }
    );

    return unsubscribe;
  }, [meetup?.id, hasChatAccess]);

  // Scroll to bottom on new messages
  useEffect(() => {
    if (messagesEndRef.current) {
      messagesEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [messages]);

  async function handleSendMessage(e?: React.FormEvent) {
    if (e) e.preventDefault();
    if (!newMessageText.trim() || !meetup?.id || !currentUser || isSending) return;

    const text = newMessageText.trim();
    setNewMessageText("");
    setIsSending(true);

    try {
      const senderName = currentUser.displayName || currentUser.email || "Thành viên";
      await addDoc(collection(db, "meetups", meetup.id, "messages"), {
        text,
        senderUid: currentUser.uid,
        senderName,
        createdAt: serverTimestamp(),
      });

      const allMembers = [
        ...(meetup.approvedUids || []),
        meetup.hostUid || meetup.host_uid || "",
      ].filter(Boolean);

      notifyMeetupChatMembers(
        meetup.id,
        meetup.title,
        allMembers,
        currentUser.uid,
        senderName,
        text
      );
    } catch (err) {
      console.error("[Firestore Chat] Send error:", err);
    } finally {
      setIsSending(false);
    }
  }

  async function handleSendJoinRequest() {
    if (!meetup?.id || !currentUser || isRequesting) return;
    setIsRequesting(true);
    try {
      await requestToJoin(meetup.id, currentUser);
    } catch (err) {
      console.error("Request join failed:", err);
    } finally {
      setIsRequesting(false);
    }
  }

  async function handleCancelRequest() {
    if (!meetup?.id || !currentUser || isRequesting) return;
    setIsRequesting(true);
    try {
      await cancelJoinRequest(meetup.id, currentUser.uid);
    } catch (err) {
      console.error("Cancel request failed:", err);
    } finally {
      setIsRequesting(false);
    }
  }

  return (
    <div className="fullscreen-chat-view flex flex-col h-[calc(100vh-120px)] md:h-[calc(100vh-160px)] gap-4 mb-5 w-full">
      {!meetup ? (
        <div className="cartoon-card no-chat-card m-auto text-center p-10 bg-white">
          <h3 className="text-xl font-bold mb-4">Chưa chọn kèo chơi nào!</h3>
          <button className="btn btn-primary" onClick={onBack}>
            Quay lại danh sách kèo
          </button>
        </div>
      ) : !hasChatAccess ? (
        <>
          {/* Top Fullscreen Header */}
          <div className="chat-top-nav cartoon-card bg-pastelCyan flex items-center gap-4 p-[14px_20px] rounded-lg shadow-neo shrink-0">
            <button type="button" className="btn btn-secondary back-btn py-2 px-4 text-[0.95rem] whitespace-nowrap" onClick={onBack}>
              ← Quay lại
            </button>

            <div className="chat-nav-details flex flex-col gap-[2px] text-left flex-1 min-w-0">
              <div className="chat-title-row flex items-center gap-[10px] flex-wrap">
                <h2 className="chat-meetup-title text-[1.3rem] font-extrabold m-0 truncate text-[#1e1e24]">{meetup.title}</h2>
                <span className="game-badge text-[0.82rem] font-extrabold bg-pastelYellow p-[2px_10px] border-2 border-[#1e1e24] rounded shadow-[1.5px_1.5px_0_#1e1e24] flex items-center gap-1">
                  <Icon name="dice" size={13} className="inline" /> {meetup.game}
                </span>
              </div>
              <span className="host-info text-[0.85rem] font-semibold text-[#1e1e24]">
                <Icon name="crown" size={13} className="mr-1 inline" /> Host:{" "}
                <strong>{meetup.host_name || meetup.hostName || "Ẩn danh"}</strong>
              </span>
            </div>
          </div>

          {/* Access Denied Private Lock Screen */}
          <div className="cartoon-card access-denied-card m-auto text-center p-[40px_24px] bg-[#fffefb] max-w-[480px] flex flex-col items-center gap-4 border-3 border-[#1e1e24] shadow-neo rounded-2xl">
            <div className="lock-big-icon text-[3.5rem]"><Icon name="lock" size={48} /></div>
            <h3 className="text-[1.5rem] font-bold">Phòng Chat Riêng Tư</h3>
            <p className="text-[0.95rem] font-semibold text-[#666666] leading-normal">
              Chỉ những người chơi đã được Host phê duyệt vào kèo mới có quyền xem và nhắn tin trong phòng chat này.
            </p>

            <div className="access-action-box mt-3 flex flex-col items-center gap-[14px] w-full">
              {!currentUser ? (
                <>
                  <p className="prompt-text text-sm font-semibold text-[#666666]">
                    <Icon name="sparkles" size={16} className="mr-1 inline" /> Hãy đăng nhập ở tab{" "}
                    <strong>Hồ sơ</strong> để gửi yêu cầu tham gia kèo.
                  </p>
                  <button className="btn btn-primary" onClick={onBack}>
                    Quay lại danh sách kèo
                  </button>
                </>
              ) : myRequest?.status === "pending" ? (
                <>
                  <div className="pending-status-pill p-[10px_16px] bg-pastelYellow border-3 border-[#1e1e24] rounded-md font-extrabold text-[0.9rem] shadow-[3px_3px_0_#1e1e24]">
                    <Icon name="clock" size={16} className="mr-1 inline" /> Yêu cầu của bạn đang chờ Host xét duyệt...
                  </div>
                  <div className="action-btn-group flex gap-3 w-full justify-center">
                    <button className="btn btn-secondary flex-1" onClick={handleCancelRequest} disabled={isRequesting}>
                      <Icon name="x" size={15} className="mr-1 inline" />
                      <span>{isRequesting ? "..." : "Hủy yêu cầu"}</span>
                    </button>
                    <button className="btn btn-primary flex-1" onClick={onBack}>
                      Quay lại danh sách
                    </button>
                  </div>
                </>
              ) : (
                <div className="action-btn-group flex gap-3 w-full justify-center">
                  <button className="btn btn-success flex-1" onClick={handleSendJoinRequest} disabled={isRequesting}>
                    <Icon name="handshake" size={15} className="mr-1 inline" />
                    <span>{isRequesting ? "Đang gửi..." : "Gửi yêu cầu tham gia kèo"}</span>
                  </button>
                  <button className="btn btn-primary flex-1" onClick={onBack}>
                    Quay lại danh sách
                  </button>
                </div>
              )}
            </div>
          </div>
        </>
      ) : (
        <>
          {/* Top Fullscreen Header */}
          <div className="chat-top-nav cartoon-card bg-pastelCyan flex items-center gap-4 p-[14px_20px] rounded-lg shadow-neo shrink-0">
            <button type="button" className="btn btn-secondary back-btn py-2 px-4 text-[0.95rem] whitespace-nowrap" onClick={onBack}>
              ← Quay lại
            </button>

            <div className="chat-nav-details flex flex-col gap-[2px] text-left flex-1 min-w-0">
              <div className="chat-title-row flex items-center gap-[10px] flex-wrap">
                <h2 className="chat-meetup-title text-[1.3rem] font-extrabold m-0 truncate text-[#1e1e24]">{meetup.title}</h2>
                <span className="game-badge text-[0.82rem] font-extrabold bg-pastelYellow p-[2px_10px] border-2 border-[#1e1e24] rounded shadow-[1.5px_1.5px_0_#1e1e24] flex items-center gap-1">
                  <Icon name="dice" size={13} className="inline" /> {meetup.game}
                </span>
              </div>
              <span className="host-info text-[0.85rem] font-semibold text-[#1e1e24]">
                <Icon name="crown" size={13} className="mr-1 inline" /> Host:{" "}
                <strong>{meetup.host_name || meetup.hostName || "Ẩn danh"}</strong>
              </span>
            </div>
          </div>

          {/* Messages Container Area */}
          <div className="chat-feed-area cartoon-card flex-1 bg-white overflow-y-auto p-5 flex flex-col rounded-lg shadow-neo border-3 border-[#1e1e24]" ref={messagesContainerRef}>
            {messages.length === 0 ? (
              <div className="chat-empty-state m-auto text-center p-[40px_20px] text-[#666666]">
                <div className="empty-icon text-[3.5rem] mb-3"><Icon name="chat" size={48} /></div>
                <h3 className="text-[1.3rem] font-bold mb-2 text-[#1e1e24]">Chưa có tin nhắn nào trong kèo này!</h3>
                <p className="text-[0.95rem] font-semibold max-w-[360px] mx-auto">
                  Hãy mở lời gửi tin nhắn đầu tiên để thảo luận và hẹn giờ chơi cùng mọi người nhé.
                </p>
              </div>
            ) : (
              <div className="messages-list flex flex-col gap-4 w-full">
                {messages.map((msg) => {
                  const isMine = currentUser && msg.senderUid === currentUser.uid;
                  const isHost = (meetup.host_uid || meetup.hostUid) === msg.senderUid;

                  return (
                    <div className={`message-row flex w-full ${isMine ? "justify-end" : "justify-start"}`} key={msg.id}>
                      <div className={`message-bubble max-w-[75%] p-4 rounded-2xl border-3 border-[#1e1e24] shadow-neo text-left flex flex-col gap-1 ${
                        isMine ? "bg-pastelPurple rounded-br-sm" : "bg-white rounded-bl-sm"
                      }`}>
                        <div className="message-author flex items-center gap-2">
                          <span className="author-name text-[0.82rem] font-extrabold text-[#1e1e24]">{msg.senderName}</span>
                          {isHost && (
                            <span className="host-badge text-[0.7rem] font-extrabold bg-pastelYellow border-[1.5px] border-[#1e1e24] p-[1px_6px] rounded-full flex items-center gap-0.5">
                              <Icon name="crown" size={11} /> Host
                            </span>
                          )}
                        </div>
                        <div className="message-text text-base font-semibold text-[#1e1e24] break-words leading-relaxed">{msg.text}</div>
                        <div className="message-time text-[0.72rem] font-bold text-[#666666] self-end">{formatMessageTime(msg.createdAt)}</div>
                      </div>
                    </div>
                  );
                })}
                <div ref={messagesEndRef} />
              </div>
            )}
          </div>

          {/* Bottom Fullscreen Input Bar */}
          <div className="chat-bottom-bar cartoon-card bg-white p-[14px_20px] rounded-lg shadow-neo shrink-0 border-3 border-[#1e1e24]">
            {currentUser ? (
              <form className="chat-input-form flex w-full gap-3" onSubmit={handleSendMessage}>
                <input
                  type="text"
                  className="cartoon-chat-input flex-1 p-4 font-semibold text-base rounded-md border-3 border-[#1e1e24] bg-[#fbf7ed] outline-none shadow-[3px_3px_0_#1e1e24] transition-all duration-150 focus:bg-white focus:shadow-[4px_4px_0_#1e1e24]"
                  placeholder="Nhập tin nhắn..."
                  value={newMessageText}
                  onChange={(e) => setNewMessageText(e.target.value)}
                  disabled={isSending}
                />
                <button
                  type="submit"
                  className="btn btn-primary send-btn py-3 px-6 text-base whitespace-nowrap"
                  disabled={!newMessageText.trim() || isSending}
                >
                  <Icon name="rocket" size={16} className="mr-1 inline" />
                  <span>{isSending ? "..." : "Gửi"}</span>
                </button>
              </form>
            ) : (
              <div className="login-chat-prompt w-full text-center text-sm font-bold text-[#666666] py-[6px]">
                <span>
                  <Icon name="lock" size={14} className="mr-1 inline" /> Bạn cần đăng nhập ở tab{" "}
                  <strong>Hồ sơ</strong> để gửi tin nhắn chat.
                </span>
              </div>
            )}
          </div>
        </>
      )}
    </div>
  );
}
