// src/lib/MeetupList.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { onAuthStateChanged, type User } from 'firebase/auth';
  import { auth } from './firebase';
  import { 
    isApprovedMember, 
    isHost, 
    requestToJoin, 
    cancelJoinRequest, 
    kickOrLeaveMember 
  } from './meetupService';
  import { navigate } from './router.svelte';


  interface Meetup {
    id: string;
    title: string;
    game: string;
    host_name?: string;
    hostName?: string;
    host_uid?: string;
    hostUid?: string;
    lat: number;
    lng: number;
    players_count?: number;
    playersCount?: number;
    players_needed?: number;
    playersNeeded?: number;
    time: string;
    color: string;
  }

  // Props — no more callback props for chat/manage/map
  interface Props {
    meetups: Meetup[];
    userLat: number | null;
    userLng: number | null;
    selectedCity: 'all' | 'HCM' | 'HN';
    selectedDistance: 'all' | '5' | '10';
    isTrackingGPS: boolean;
    gpsError: boolean;
  }

  let { 
    meetups, 
    userLat, 
    userLng, 
    selectedCity = $bindable('all'), 
    selectedDistance = $bindable('all'),
    isTrackingGPS,
    gpsError,
  }: Props = $props();


  let currentUser = $state<User | null>(auth.currentUser);
  let unsubscribeAuth: (() => void) | null = null;
  let isActionProcessing = $state<boolean>(false);

  onMount(() => {
    unsubscribeAuth = onAuthStateChanged(auth, (user) => {
      currentUser = user;
    });
  });

  onDestroy(() => {
    if (unsubscribeAuth) unsubscribeAuth();
  });


  async function handleJoinRequest(meetup: Meetup) {
    if (!currentUser || isActionProcessing) return;
    isActionProcessing = true;
    try {
      await requestToJoin(meetup.id, currentUser);
    } catch (err) {
      console.error('Request join error:', err);
    } finally {
      isActionProcessing = false;
    }
  }

  async function handleCancel(meetup: Meetup) {
    if (!currentUser || isActionProcessing) return;
    isActionProcessing = true;
    try {
      await cancelJoinRequest(meetup.id, currentUser.uid);
    } catch (err) {
      console.error('Cancel request error:', err);
    } finally {
      isActionProcessing = false;
    }
  }

  async function handleLeave(meetup: Meetup) {
    if (!currentUser || isActionProcessing) return;
    isActionProcessing = true;
    try {
      await kickOrLeaveMember(meetup.id, currentUser.uid);
    } catch (err) {
      console.error('Leave meetup error:', err);
    } finally {
      isActionProcessing = false;
    }
  }

  function calculateDistance(lat1: number, lon1: number, lat2: number, lon2: number): number {

    const R = 6371; // km
    const dLat = (lat2 - lat1) * Math.PI / 180;
    const dLon = (lon2 - lon1) * Math.PI / 180;
    const a = 
      Math.sin(dLat/2) * Math.sin(dLat/2) +
      Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * 
      Math.sin(dLon/2) * Math.sin(dLon/2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
    return R * c;
  }

  function getMeetupCity(meetup: Meetup): 'HCM' | 'HN' {
    const distToHCM = calculateDistance(meetup.lat, meetup.lng, 10.7769, 106.7009);
    const distToHN = calculateDistance(meetup.lat, meetup.lng, 21.0285, 105.8542);
    return distToHN < distToHCM ? 'HN' : 'HCM';
  }

  function formatTime(timeStr: string): string {
    if (!timeStr) return '';
    if (!timeStr.includes('T')) return timeStr;
    try {
      const date = new Date(timeStr);
      const day = String(date.getDate()).padStart(2, '0');
      const month = String(date.getMonth() + 1).padStart(2, '0');
      const year = date.getFullYear();
      const hours = String(date.getHours()).padStart(2, '0');
      const minutes = String(date.getMinutes()).padStart(2, '0');
      return `${hours}:${minutes}, ${day}/${month}/${year}`;
    } catch {
      return timeStr;
    }
  }

  // Navigate instead of opening local modal for filter and map
  function openFilter() { navigate({ name: 'filter' }); }
  function openMap() { navigate({ name: 'map', mode: 'discover' }); }
</script>

<div class="meetup-list-container">
  <!-- Cartoon Trigger Bar for Search Filter Modal -->
  <div class="cartoon-card filter-trigger-card">
    <div class="filter-trigger-info">
      <div class="filter-trigger-header">
        <span class="filter-title-icon">🎲</span>
        <h3>Danh Sách Kèo Chơi Boardgame</h3>
      </div>
      
      <!-- Active Filter Badges -->
      <div class="active-filter-badges">
        <span class="badge-chip">
          📍 Khu vực: <strong>{selectedCity === 'all' ? 'Tất cả' : selectedCity === 'HCM' ? 'TP. HCM' : 'Hà Nội'}</strong>
        </span>
        <span class="badge-chip">
          📏 Khoảng cách: <strong>{selectedDistance === 'all' ? 'Mọi khoảng cách' : `< ${selectedDistance} km`}</strong>
        </span>
        {#if userLat !== null}
          <span class="badge-chip gps-on-chip">
            🎯 GPS Bật
          </span>
        {/if}
      </div>
    </div>

    <button type="button" class="btn btn-primary filter-trigger-btn" onclick={openFilter}>
      🔍 Bộ Lọc Tìm Kiếm ⚙️
    </button>
  </div>


  <!-- Meetups Cards Grid -->

  <div class="meetup-cards-grid">
    {#if meetups.length === 0}
      <div class="cartoon-card no-meetup-card">
        <h3>Không tìm thấy kèo chơi nào phù hợp! 😢</h3>
        <p>Thử đổi bộ lọc hoặc nhấp chuột lên bản đồ để tự lên kèo mới nhé!</p>
      </div>
    {:else}
      {#each meetups as meetup (meetup.id)}
        {@const city = getMeetupCity(meetup)}
        {@const distance = userLat !== null && userLng !== null ? calculateDistance(userLat, userLng, meetup.lat, meetup.lng) : null}
        {@const userIsHost = isHost(meetup, currentUser?.uid)}
        {@const userIsMember = isApprovedMember(meetup, currentUser?.uid)}

        
        <div class="cartoon-card meetup-item-card" style="border-top: 10px solid {meetup.color};">
          <!-- Card Badge info -->
          <div class="meetup-card-badges">
            <span class="city-badge {city === 'HCM' ? 'hcm-color' : 'hn-color'}">
              {city === 'HCM' ? '🌆 HCM' : '🏰 HN'}
            </span>
            {#if distance !== null}
              <span class="distance-badge">
                📍 Cách {distance.toFixed(1)} km
              </span>
            {/if}
            {#if userIsHost}
              <span class="membership-badge host-tag">👑 Host</span>
            {:else if userIsMember}
              <span class="membership-badge member-tag">✅ Đã tham gia</span>
            {/if}
          </div>

          <h3 class="meetup-card-title">{meetup.title}</h3>
          
          <div class="meetup-card-details">
            <div class="detail-row">
              <span class="detail-icon">🎲</span>
              <span>Game: <strong>{meetup.game}</strong></span>
            </div>
            <div class="detail-row">
              <span class="detail-icon">⏰</span>
              <span>Lịch: <strong>{formatTime(meetup.time)}</strong></span>
            </div>
            <div class="detail-row">
              <span class="detail-icon">👥</span>
              <span>Sĩ số: <strong>{meetup.players_count || meetup.playersCount || 1} / {meetup.players_needed || meetup.playersNeeded || 4} người</strong></span>
            </div>
            <div class="detail-row">
              <span class="detail-icon">👤</span>
              <span>Host: <strong>{meetup.host_name || meetup.hostName || 'Ẩn danh'}</strong></span>
            </div>
          </div>

          <div class="card-action-row">
            <button class="btn btn-secondary action-btn" onclick={() => navigate({ name: 'map', mode: 'discover' })}>
              Vị trí 🗺️
            </button>

            {#if userIsMember}
              <button class="btn btn-primary action-btn" onclick={() => navigate({ name: 'chat', meetup })}>
                Chat 💬
              </button>
            {/if}

            {#if userIsHost}
              <button class="btn btn-success action-btn" onclick={() => navigate({ name: 'manage', meetup })}>
                Duyệt 👥
              </button>
            {:else if userIsMember}
              <button class="btn btn-secondary action-btn leave-btn" onclick={() => handleLeave(meetup)} disabled={isActionProcessing}>
                Rời 🚪
              </button>
            {:else if currentUser}
              <button class="btn btn-success action-btn" onclick={() => handleJoinRequest(meetup)} disabled={isActionProcessing}>
                {isActionProcessing ? '...' : 'Xin vào 🤝'}
              </button>
            {/if}
          </div>
        </div>
      {/each}
    {/if}
  </div>
</div>




<style>
  .meetup-list-container {
    width: 100%;
    margin-top: 24px;
    display: flex;
    flex-direction: column;
    gap: 32px;
  }

  .filter-trigger-card {
    background-color: #fffefb;
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 16px;
    padding: 20px 24px;
    flex-wrap: wrap;
  }

  @media (max-width: 600px) {
    .filter-trigger-card {
      flex-direction: column;
      align-items: stretch;
    }
    .filter-trigger-btn {
      width: 100%;
    }
  }

  .filter-trigger-info {
    display: flex;
    flex-direction: column;
    gap: 8px;
    text-align: left;
  }

  .filter-trigger-header {
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .filter-trigger-header h3 {
    font-size: 1.3rem;
    font-weight: 800;
  }

  .active-filter-badges {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
  }

  .badge-chip {
    font-size: 0.85rem;
    font-weight: 600;
    padding: 4px 12px;
    background-color: var(--bg-secondary);
    border: var(--border-width-sm) solid var(--color-border);
    border-radius: 100px;
    color: var(--text-dark);
    box-shadow: 1.5px 1.5px 0 var(--color-border);
  }

  .gps-on-chip {
    background-color: var(--pastel-green);
  }

  .filter-trigger-btn {
    font-size: 1rem;
    padding: 10px 20px;
    white-space: nowrap;
  }

  /* Cards Grid */
  .meetup-cards-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
    gap: 24px;
  }

  @media (max-width: 480px) {
    .meetup-cards-grid {
      grid-template-columns: 1fr;
    }
  }

  .no-meetup-card {
    grid-column: 1 / -1;
    text-align: center;
    background-color: #fff;
    padding: 40px 20px;
  }

  .no-meetup-card p {
    color: var(--text-muted);
    font-weight: 500;
    margin-top: 8px;
  }

  /* Item Card styling */
  .meetup-item-card {
    background-color: #fffefc;
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    text-align: left;
    padding: 20px;
  }

  .meetup-card-badges {
    display: flex;
    gap: 8px;
    margin-bottom: 12px;
  }

  .city-badge, .distance-badge {
    font-size: 0.8rem;
    font-weight: 700;
    padding: 4px 10px;
    border-radius: 100px;
    border: var(--border-width-sm) solid var(--color-border);
    box-shadow: 1.5px 1.5px 0 var(--color-border);
  }

  .city-badge.hcm-color {
    background-color: var(--pastel-pink);
  }

  .city-badge.hn-color {
    background-color: var(--pastel-green);
  }

  .distance-badge {
    background-color: var(--pastel-cyan);
  }

  .meetup-card-title {
    font-size: 1.25rem;
    font-weight: 700;
    margin-bottom: 16px;
    line-height: 1.3;
    color: var(--text-dark);
  }

  .meetup-card-details {
    width: 100%;
    display: flex;
    flex-direction: column;
    gap: 8px;
    margin-bottom: 20px;
  }

  .detail-row {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 0.9rem;
    color: var(--text-dark);
    font-weight: 500;
  }

  .detail-icon {
    font-size: 1.1rem;
  }

  .card-action-row {

    width: 100%;
    display: flex;
    gap: 10px;
    margin-top: auto;
  }

  .action-btn {
    flex: 1;
    padding: 10px 12px !important;
    font-size: 0.9rem !important;
    white-space: nowrap;
  }

  .leave-btn {
    background-color: var(--pastel-pink) !important;
  }

  .membership-badge {
    font-size: 0.8rem;
    font-weight: 800;
    padding: 4px 10px;
    border-radius: 100px;
    border: var(--border-width-sm) solid var(--color-border);
    box-shadow: 1.5px 1.5px 0 var(--color-border);
  }

  .host-tag {
    background-color: var(--pastel-yellow);
  }

  .member-tag {
    background-color: var(--pastel-green);
  }
</style>

// src/components/MeetupList.tsx
import React, { useState, useEffect } from "react";
import { onAuthStateChanged, type User } from "firebase/auth";
import { auth } from "../libs/firebase";
import { navigate, navigateToTab } from "../libs/router";
import Icon from "./Icon";

import {
  isApprovedMember,
  isHost,
  requestToJoin,
  cancelJoinRequest,
  subscribeToMeetupRequests,
  confirmParticipation,
  type MeetupRequest,
} from "../api/meetupService";

import { calculateDistance, getMeetupCity } from "../utils/geo";
import { formatTime } from "../utils/time";

interface Meetup {
  id: string;
  title: string;
  game: string;
  hostName?: string;
  host_name?: string;
  hostUid?: string;
  host_uid?: string;
  playersCount?: number;
  players_count?: number;
  playersNeeded?: number;
  players_needed?: number;
  time: string;
  lat: number;
  lng: number;
  color?: string;
  approvedUids?: string[];
  confirmedUids?: string[];
}

interface Props {
  meetups: Meetup[];
  selectedCity: "all" | "HCM" | "HN";
  selectedDistance: "all" | "5" | "10";
  userLat: number | null;
  userLng: number | null;
  isTrackingGPS: boolean;
  gpsError: boolean;
  onSelectMeetupOnMap?: (meetupId: string, lat: number, lng: number) => void;
  isLoading?: boolean;
}

export default function MeetupList({
  meetups,
  selectedCity,
  selectedDistance,
  userLat,
  userLng,
  isTrackingGPS,
  gpsError,
  onSelectMeetupOnMap,
  isLoading = false,
}: Props) {
  const [currentUser, setCurrentUser] = useState<User | null>(auth.currentUser);

  // Sync auth state
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      setCurrentUser(user);
    });
    return unsubscribe;
  }, []);

  return (
    <div className="meetup-list-comp flex flex-col gap-4 text-left">
      {isLoading ? (
        <div className="skeleton-meetup-list flex flex-col gap-4">
          {[1, 2, 3].map((n) => (
            <div className="cartoon-card meetup-card skeleton-card bg-white p-5 border-3 border-[#1e1e24] rounded-2xl shadow-neo flex flex-col gap-3.5" key={n}>
              <div className="skeleton skeleton-line long h-5 bg-gray-200 rounded w-2/3"></div>
              <div className="skeleton skeleton-line medium h-4 bg-gray-200 rounded w-1/2"></div>
              <div className="flex gap-2">
                <div className="skeleton skeleton-badge w-20 h-6 bg-gray-200 rounded-full"></div>
                <div className="skeleton skeleton-badge w-24 h-6 bg-gray-200 rounded-full"></div>
              </div>
            </div>
          ))}
        </div>
      ) : meetups.length === 0 ? (
        <div className="cartoon-card empty-card text-center p-10 bg-white border-3 border-[#1e1e24] rounded-2xl shadow-neo flex flex-col items-center gap-3">
          <div className="empty-state-icon text-[3.5rem]"><Icon name="dice" size={48} /></div>
          <h3 className="text-xl font-bold text-[#1e1e24]">Không tìm thấy kèo chơi phù hợp!</h3>
          <p className="text-sm font-semibold text-[#666666] max-w-[340px] leading-relaxed">
            Hiện tại không có kèo nào khớp với bộ lọc thành phố hoặc khoảng cách của bạn. Bạn hãy đổi bộ lọc hoặc tự mình lên kèo mới nhé!
          </p>
          <button className="btn btn-primary mt-2" onClick={() => navigateToTab("create")}>
            <Icon name="plus" size={16} className="mr-1 inline" /> Tự lên kèo chơi mới
          </button>
        </div>
      ) : (
        <div className="meetups-list-grid flex flex-col gap-4">
          {meetups.map((m) => (
            <MeetupCard
              key={m.id}
              meetup={m}
              currentUser={currentUser}
              userLat={userLat}
              userLng={userLng}
              onSelectOnMap={onSelectMeetupOnMap}
            />
          ))}
        </div>
      )}
    </div>
  );
}

// ── INNER COMPONENT: MeetupCard (Subscribes to its own requests state) ──────
function MeetupCard({
  meetup,
  currentUser,
  userLat,
  userLng,
  onSelectOnMap,
}: {
  meetup: Meetup;
  currentUser: User | null;
  userLat: number | null;
  userLng: number | null;
  onSelectOnMap?: (meetupId: string, lat: number, lng: number) => void;
}) {
  const [requests, setRequests] = useState<MeetupRequest[]>([]);
  const [isActionLoading, setIsActionLoading] = useState<boolean>(false);

  useEffect(() => {
    if (meetup.id) {
      const unsubscribe = subscribeToMeetupRequests(meetup.id, (list) => {
        setRequests(list);
      });
      return unsubscribe;
    }
  }, [meetup.id]);

  const count = meetup.playersCount || meetup.players_count || 1;
  const needed = meetup.playersNeeded || meetup.players_needed || 4;
  const hostName = meetup.hostName || meetup.host_name || "Ẩn danh";
  const hostUid = meetup.hostUid || meetup.host_uid;

  const isUserHost = isHost(meetup, currentUser?.uid);
  const isApproved = isApprovedMember(meetup, currentUser?.uid);

  // Check if player has sent request
  const myRequest = currentUser ? requests.find((r) => r.uid === currentUser.uid) || null : null;
  const isPending = myRequest?.status === "pending";

  const isFull = count >= needed;

  // Check confirmation status
  const confirmedUids = meetup.confirmedUids || [];
  const isConfirmed = currentUser ? confirmedUids.includes(currentUser.uid) : false;

  // Calculate distance
  const distance =
    userLat !== null && userLng !== null
      ? calculateDistance(userLat, userLng, meetup.lat, meetup.lng)
      : null;

  async function handleJoinRequest() {
    if (!currentUser || isActionLoading) return;
    setIsActionLoading(true);
    try {
      await requestToJoin(meetup.id, currentUser);
    } catch (e: any) {
      alert(e.message || "Không thể gửi yêu cầu tham gia!");
    } finally {
      setIsActionLoading(false);
    }
  }

  async function handleCancelRequest() {
    if (!currentUser || isActionLoading) return;
    setIsActionLoading(true);
    try {
      await cancelJoinRequest(meetup.id, currentUser.uid);
    } catch (e: any) {
      alert(e.message || "Không thể hủy yêu cầu!");
    } finally {
      setIsActionLoading(false);
    }
  }

  async function handleConfirmParticipation() {
    if (!currentUser || isActionLoading) return;
    setIsActionLoading(true);
    try {
      const name = currentUser.displayName || currentUser.email || "Thành viên";
      await confirmParticipation(meetup.id, currentUser.uid, name);
    } catch (e: any) {
      alert(e.message || "Xác nhận tham gia kèo thất bại!");
    } finally {
      setIsActionLoading(false);
    }
  }

  return (
    <div
      className="cartoon-card meetup-card bg-white p-5 border-3 border-[#1e1e24] rounded-2xl shadow-neo flex flex-col gap-3.5 text-left transition-all duration-100 hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[6px_6px_0px_#1e1e24]"
      style={{ borderLeft: `8px solid ${meetup.color || "#bca0f5"}` }}
    >
      <div className="card-top-header flex justify-between items-start gap-3 w-full">
        <div className="card-title-block flex-1 min-w-0">
          <h3 className="meetup-title-text font-extrabold text-[1.12rem] text-[#1e1e24] m-0 mb-1 leading-snug line-clamp-2">
            {meetup.title}
          </h3>
          <span className="meetup-game flex items-center gap-1.5 text-xs font-bold text-[#666666]">
            <Icon name="dice" size={13} className="inline" /> Game: <strong>{meetup.game}</strong>
          </span>
        </div>
        {distance !== null && (
          <span className="distance-badge font-extrabold text-[0.72rem] bg-pastelCyan border-2 border-[#1e1e24] p-[3px_8px] rounded-full shadow-[1.5px_1.5px_0_#1e1e24] flex items-center gap-1 shrink-0">
            <Icon name="distance" size={11} className="inline" /> {distance.toFixed(1)} km
          </span>
        )}
      </div>

      <div className="meetup-card-body flex flex-col gap-2 border-t-2 border-b-2 border-dashed border-[#1e1e24] py-3 text-xs font-semibold text-[#1e1e24]">
        <div className="meetup-info-row flex items-center gap-1.5">
          <Icon name="clock" size={13} className="inline text-[#666666]" />
          <span>Giờ chơi: <strong>{formatTime(meetup.time)}</strong></span>
        </div>
        <div className="meetup-info-row flex items-center gap-1.5">
          <Icon name="users" size={13} className="inline text-[#666666]" />
          <span>Sĩ số kèo: <strong>{count}/{needed} người</strong></span>
        </div>
        <div className="meetup-info-row flex items-center gap-1.5">
          <Icon name="user" size={13} className="inline text-[#666666]" />
          <span>Host của kèo: <strong>{hostName}</strong></span>
        </div>
      </div>

      <div className="card-actions flex flex-wrap gap-2.5 items-center justify-between mt-1">
        <div className="left-side-actions flex gap-2 flex-wrap">
          {isUserHost ? (
            <button
              type="button"
              className="btn btn-primary text-xs py-2 px-4 inline-flex items-center gap-1 bg-[#ffa4b2]"
              onClick={() => navigate({ name: "manage", meetupId: meetup.id })}
            >
              <Icon name="settings" size={13} className="inline" /> Quản lý kèo
            </button>
          ) : isApproved ? (
            <>
              <button
                type="button"
                className="btn btn-success text-xs py-2 px-4 inline-flex items-center gap-1"
                onClick={() => navigate({ name: "chat", meetupId: meetup.id })}
              >
                <Icon name="chat" size={13} className="inline" /> Vào chat box
              </button>
              {!isConfirmed && (
                <button
                  type="button"
                  className="btn btn-primary text-xs py-2 px-4 inline-flex items-center gap-1 bg-pastelYellow"
                  onClick={handleConfirmParticipation}
                  disabled={isActionLoading}
                >
                  <Icon name="check" size={13} className="inline" />
                  <span>{isActionLoading ? "..." : "Xác nhận tham gia"}</span>
                </button>
              )}
              {isConfirmed && (
                <span className="text-[0.7rem] font-bold text-[#10b981] flex items-center gap-0.5 bg-[#e6fcf5] border border-[#10b981] p-[2px_6px] rounded">
                  <Icon name="check-circle" size={12} className="inline" /> Đã xác nhận chơi
                </span>
              )}
            </>
          ) : isPending ? (
            <button
              type="button"
              className="btn btn-secondary text-xs py-2 px-4 inline-flex items-center gap-1"
              onClick={handleCancelRequest}
              disabled={isActionLoading}
            >
              <Icon name="x" size={13} className="inline" />
              <span>{isActionLoading ? "Đang hủy..." : "Hủy yêu cầu"}</span>
            </button>
          ) : currentUser ? (
            <button
              type="button"
              className={`btn text-xs py-2 px-4 inline-flex items-center gap-1 border-2 border-[#1e1e24] rounded-md font-bold shadow-[2px_2px_0_#1e1e24] ${
                isFull ? "bg-gray-100 text-gray-400 cursor-not-allowed shadow-none border-gray-300" : "btn-success bg-[#9ee3b2]"
              }`}
              onClick={handleJoinRequest}
              disabled={isActionLoading || isFull}
            >
              <Icon name="plus" size={13} className="inline" />
              <span>{isFull ? "Kèo đã đầy" : isActionLoading ? "Đang gửi..." : "Xin tham gia"}</span>
            </button>
          ) : (
            <span className="text-[0.7rem] font-bold text-[#666666] italic bg-[#fbf7ed] p-[4px_8px] rounded border border-gray-300">
              Đăng nhập để xin tham gia kèo
            </span>
          )}
        </div>

        {onSelectOnMap && (
          <button
            type="button"
            className="btn btn-secondary text-xs py-2 px-3 inline-flex items-center gap-1 self-end whitespace-nowrap bg-white border-[#1e1e24]"
            onClick={() => onSelectOnMap(meetup.id, meetup.lat, meetup.lng)}
          >
            <Icon name="map-pin" size={13} className="inline" /> Nhìn bản đồ
          </button>
        )}
      </div>
    </div>
  );
}
